version: "3"

services:
  app:
    network_mode: bridge
    build:
      context: .
      dockerfile: Dockerfile

    ports:
    - "8000:8000"

    environment:
      DB_NAME: postgres
      PORT: 5432
      DB_USER: postgres
      PASSWORD: postgres
      HOST: 172.17.0.2
